_target_: deeprootgen.data_model.FormModel
components:
  parameters:
    collapsible: true
    children:
      - id: select-x-axis-dropdown
        param: x_axis_column
        label: X axis
        help: Select the column for the x axis
        class_name: dash.dcc.Dropdown
        handler: dropdown
        options_func: list
        kwargs:
          multi: false
          searchable: true
          clearable: true
          placeholder: Select x axis
          persistence: true
      - id: select-y-axis-dropdown
        param: y_axis_column
        label: Y axis
        help: Select the column for the y axis
        class_name: dash.dcc.Dropdown
        handler: dropdown
        options_func: list
        kwargs:
          multi: false
          searchable: true
          clearable: true
          placeholder: Select y axis
          persistence: true
      - id: select-group-by-dropdown
        param: group_by_column
        label: Group by
        help: Select the column to group data by
        class_name: dash.dcc.Dropdown
        handler: dropdown
        options_func: list
        kwargs:
          multi: false
          searchable: true
          clearable: true
          placeholder: Select group by
          persistence: true
      - id: select-x-summary-stats-dropdown
        param: x_summary_statistics
        label: X summary statistic
        help: Select summary statistics for the X axis visualisation
        class_name: dash.dcc.Dropdown
        handler: dropdown
        options_func: deeprootgen.statistics.get_summary_statistics
        kwargs:
          multi: false
          searchable: true
          clearable: true
          placeholder: Select left summary statistic
          persistence: true
      - id: select-y-summary-stats-dropdown
        param: y_summary_statistics
        label: Y summary statistic
        help: Select summary statistics for the y visualisation
        class_name: dash.dcc.Dropdown
        handler: dropdown
        options_func: deeprootgen.statistics.get_summary_statistics
        kwargs:
          multi: false
          searchable: true
          clearable: true
          placeholder: Select right summary statistic
          persistence: true
  simulated_data:
    collapsible: true
    children:
      - id: upload-node-data-file-button
        label: Upload  
        help: Upload simulated data from a csv file
        class_name: dash.dcc.Upload
        handler: file_upload
        kwargs:
          children: Load simulation data
      - id: clear-obs-data-file-button
        label: Clear
        help: Clear the simulated root data from the form
        class_name: dash_bootstrap_components.Button 
        kwargs:
          children: Clear simulation data
          color: primary
          className: me-1
  results:
    children:
      - id: histogram-x-plot
        label: X histogram
        help: Histogram for data on the x axis
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: histogram-y-plot
        label: Y histogram
        help: Histogram for data on the y axis
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: box-x-plot
        label: X box
        help: Box plot for data on the x axis
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: box-y-plot
        label: Y box
        help: Box plot for data on the y axis
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: scatter-xy-plot
        label: Scatter 
        help: Scatter plot for the data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: heatmap-xy-plot
        label: Heatmap 
        help: Heatmap plot for the data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: x-summary-statistic-plot
        label: X summary statistic
        help: Visualisation for summary statistic data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: y-summary-statistic-plot
        label: Y summary statistic
        help: Visualisation for summary statistic data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: scatter-statistics-plot
        label: Statistics scatter
        help: Scatter plot for X and Y summary statistic data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto
      - id: heatmap-statistics-plot
        label: Statistics heatmap
        help: Heatmap plot for X and Y summary statistic data
        class_name: dash.dcc.Graph 
        kwargs:
          responsive: auto