defaults:
  - _self_
  - calibration_form: common
  - deployments_form: common
  - eda_form: common
  - experiment: mlflow
  - object_storage: minio
  - orchestration: prefect
  - simulation_form: common
