name: Docker Build

on: 
  workflow_dispatch: {}

permissions:
  actions: write
  packages: write
  
jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker build
      run: bash scripts/docker/build.sh mlflow
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
    - name: Docker push
      run: bash scripts/docker/push.sh mlflow