name: Tests

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches: 
      - main
  push:
    branches: 
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
         poetry install --no-interaction

    - name: Lint code
      run: |
        source .venv/bin/activate
        flake8 --count --show-source --statistics

    - name: Test code
      run: |
        export CICD_TESTING_ENV=true

        source .venv/bin/activate
        pytest --cov=deeprootgen --junit-xml=test_results.xml